[package]
name = "unicode-matching"
version = "0.1.0"
edition = "2021"
description = "Rust library crate to match open/close Unicode graphemes for brackets/quotes)"
license = "MIT"
repository = "https://github.com/qtfkwk/unicode-matching"

[dependencies]
