[package]
name = "unicode-matching"
version = "0.5.3"
edition = "2021"
description = "Rust library crate to match Unicode open/close brackets"
license = "MIT"
repository = "https://github.com/qtfkwk/unicode-matching"

[dependencies]
gstring = "0.9.0"
